#!/usr/bin/env python2
"""
A dumb alternative to awk for Python users. Useful as a tool called from vim.
Meant to replace cantrips like `awk '{print $2}'` in day-to-day usage.
See README for details
"""
# Libraries available while parsing
import sys
import re
import json


def parse_argv_word_indices(user_input):
    indices = user_input.split(',')
    return [int(i) for i in indices]


def print_stdin_word_indices(indices):
    for line in sys.stdin:
        try:
            words = line.split()
            print ' '.join([words[i] for i in indices])
        except:
            pass


def exec_argv_as_python(user_input):
    for line in sys.stdin:
        try:
            words = line.split()
            tabs = line.split('\t')
            commas = line.split(',')
            w = words
            t = tabs
            c = commas
            cmd = 'val = ' + user_input
            exec(cmd)
            if type(val) is list:
                if val:
                    print ' '.join(val)
            elif val is not None:
                print(val)
        except:
            pass


def main():
    user_input = ' '.join(sys.argv[1:])
    try:
        indices = parse_argv_word_indices(user_input)
        print_stdin_word_indices(indices)
        return
    except:
        pass
    exec_argv_as_python(user_input)


if __name__ == '__main__':
    main()

